name: Gerar APK Expo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar Expo CLI e EAS CLI
        run: npm install -g expo-cli eas-cli

      - name: Configurar Credencial Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Executar Build do APK no EAS
        run: eas build --platform android --profile preview --non-interactive
